### ISSUE TITLE
com.github.jreddit.utils.restclient missing

### ISSUE THREAD

**Issue by dasmikko** [karan/jReddit#100] opened 2014-10-07 06:46 UTC
I can't use the ```import com.github.jreddit.utils.restclient``` as is says it's not there.

my code:
```
import com.github.jreddit.submissions.Submission;
import com.github.jreddit.submissions.Submissions;
import com.github.jreddit.utils.restclient.PoliteRestClient;
import com.github.jreddit.utils.restclient.RestClient;

import org.androidannotations.annotations.Background;
import org.androidannotations.annotations.EActivity;
import org.androidannotations.annotations.ViewById;

import java.util.List;

@EActivity(R.layout.activity_main)
public class MainActivity extends Activity {

    @ViewById(R.id.submissinList)
    ListView submissionList;

    @Background
    void load_submissions()
    {
        RestClient restClient = new HttpRestClient();
        restClient.setUserAgent("bot/1.0 by name");

        // Handle to Submissions, which offers the basic API submission functionality
        Submissions subms = new Submissions(restClient, user);

        // Retrieve submissions of a submission
        List<Submission> submissionsSubreddit = subms.ofSubreddit("programming", SubmissionSort.TOP, -1, 100, null, null, true);

    }
}
```

**Comment by sfat** [comment] 2015-01-08 19:27
closing this as duplicate of #102. @dasmikko can you go ahead and create an issue regarding the gradle/maven guide that you are interested in?

**Closed by sfat** 2015-01-08 19:27 UTC
