### ISSUE TITLE
Missing classes

### ISSUE THREAD

**Issue by droideparanoico** [karan/jReddit#91] opened 2014-08-06 16:26 UTC
I'm trying to use jReddit on my project, but when I add it via gradle into Intellij Idea there's a lot of classes missing. For example, the whole folders "comment" and "exception" are missing. The same thing when I download the jar from the maven repository. Am I doing something wrong?

**Comment by sfat** [comment] 2015-01-08 19:28
closing this as duplicate of #102.

**Closed by sfat** 2015-01-08 19:28 UTC
